import { Input } from "components/ui";

export const USER_SUBTYPE_OPTIONS = [
  { label: "SNF_ALF", value: 1 },
  { label: "MEDICAL_CENTERS", value: 2 },
  { label: "HMO", value: 3 },
  { label: "WORKERS_COMP", value: 4 },
];

export const PROVIDER_FIELD_CONSTANT = [
  {
    name: "firstName",
    label: "First Name",
    type: "text",
    component: Input,
    placeholder: "Enter first name",
    isBasic: true,
  },
  {
    name: "lastName",
    label: "Last Name",
    type: "text",
    component: Input,
    placeholder: "Enter last name",
    isBasic: true,
  },
  {
    name: "companyName",
    label: "Company Name",
    type: "text",
    component: Input,
    placeholder: "Enter company name",
    isBasic: true,
  },
  {
    name: "phoneNumber",
    countryCode: "countryCode",
    label: "Mobile No.",
    component: "phoneNumber",
    placeholder: "Enter mobile no.",
  },
  {
    name: "email",
    label: "Email",
    type: "text",
    component: Input,
    placeholder: "Enter email",
    isBasic: true,
  },
  {
    name: "password",
    label: "Password",
    type: "password",
    component: "password",
    placeholder: "Enter Password",
    ishidden: true,
  },
  {
    name: "userSubType",
    label: "Provider Type",
    component: "select",
    option: USER_SUBTYPE_OPTIONS,
    placeholder: "Enter provider type",
  },
  {
    name: "gender",
    label: "Gender",
    type: "number",
    component: "radio",
  },
  {
    name: "dob",
    label: "DOB",
    component: "datepicker",
  },
  {
    name: "address",
    label: "Address",
    type: "text",
    component: Input,
    placeholder: "Enter address",
    textArea: true,
    isBasic: true,
  },
  {
    name: "state",
    label: "State",
    type: "text",
    component: "asyncSelect",
    placeholder: "Enter State",
  },
  {
    name: "country",
    label: "Country",
    type: "text",
    component: Input,
    placeholder: "Enter country",
    isBasic: true,
  },
  {
    name: "city",
    label: "City",
    type: "text",
    component: Input,
    placeholder: "Enter city",
    isBasic: true,
  },
  {
    name: "pincode",
    label: "Pincode",
    type: "text",
    component: Input,
    placeholder: "Enter pincode",
    isBasic: true,
  },
  {
    name: "alternatePhoneNumber",
    countryCode: "alternateCountryCode",
    component: "phoneNumber",
    label: "Alternate Mobile No.",
    placeholder: "Enter alternate mobile no.",
  },
];
