import { Input } from "components/ui";

export const JOB_TYPE_OPTIONS = [
  { label: "Clinician", value: 1 },
  { label: "Technician", value: 2 },
];

export const STAFF_FIELD_CONSTANT = [
  {
    name: "enrollmentNumber",
    label: "Enrollment Number",
    type: "text",
    component: Input,
    placeholder: "Enter enrollment number",
    isBasic: true,
  },
  {
    name: "firstName",
    label: "First Name",
    type: "text",
    component: Input,
    placeholder: "Enter first name",
    isBasic: true,
  },
  {
    name: "lastName",
    label: "Last Name",
    type: "text",
    component: Input,
    placeholder: "Enter last name",
    isBasic: true,
  },
  {
    name: "phoneNumber",
    countryCode: "countryCode",
    label: "Mobile No.",
    component: "phoneNumber",
    placeholder: "Enter mobile no.",
  },
  {
    name: "email",
    label: "Email",
    type: "text",
    component: Input,
    placeholder: "Enter email",
    isBasic: true,
  },
  {
    name: "password",
    label: "Password",
    type: "password",
    component: "password",
    placeholder: "Enter Password",
    ishidden: true,
  },
  {
    name: "jobType",
    label: "Job Type",
    component: "select",
    option: JOB_TYPE_OPTIONS,
    placeholder: "Enter job type",
  },
  {
    name: "gender",
    label: "Gender",
    type: "number",
    component: "radio",
  },
  {
    name: "dob",
    label: "DOB",
    component: "datepicker",
  },
  {
    name: "address",
    label: "Address",
    type: "text",
    component: Input,
    placeholder: "Enter address",
    textArea: true,
    isBasic: true,
  },
  {
    name: "state",
    label: "State",
    type: "text",
    component: "asyncSelect",
    placeholder: "Enter State",
  },
  {
    name: "country",
    label: "Country",
    type: "text",
    component: Input,
    placeholder: "Enter country",
    isBasic: true,
  },
  {
    name: "city",
    label: "City",
    type: "text",
    component: Input,
    placeholder: "Enter city",
    isBasic: true,
  },
  {
    name: "pincode",
    label: "Pincode",
    type: "text",
    component: Input,
    placeholder: "Enter pincode",
    isBasic: true,
  },
  {
    name: "alternatePhoneNumber",
    countryCode: "alternateCountryCode",
    component: "phoneNumber",
    label: "Alternate Mobile No.",
    placeholder: "Enter alternate mobile no.",
  },
];
